import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://b2b-io--cpqpro.sandbox.my.salesforce.com/');
  await page.getByRole('textbox', { name: 'Username' }).press('ControlOrMeta+v');
  await page.getByRole('textbox', { name: 'Username' }).fill('o.harliansyah@ioh.co.id.cpqpro');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).press('ControlOrMeta+v');
  await page.getByRole('textbox', { name: 'Password' }).fill('QFbe3fqe1osXwA');
  await page.getByRole('button', { name: 'Log In to Sandbox' }).click();
  await page.getByRole('link', { name: 'Opportunities' }).click();
  await page.getByRole('link', { name: 'PETROMAS PERTIWI-LA CUST' }).first().click();
  await page.getByRole('tab', { name: 'Score Card' }).click();
  await page.getByRole('button', { name: 'Edit Partnership Tier with' }).click();
  await page.getByRole('combobox', { name: 'Partnership Tier with Principal', exact: true }).click();
  await page.getByRole('option', { name: 'Highest Partnership' }).click();
  await page.getByRole('combobox', { name: 'Deal Registered', exact: true }).click();
  await page.getByRole('option', { name: 'Yes' }).click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.locator('a').filter({ hasText: 'Quoting' }).click();
  await page.locator('button').filter({ hasText: 'Mark as Current Stage' }).click();
  await expect(page.locator('div').filter({ hasText: 'Success notification.Stage' }).nth(3)).toBeVisible();
  await page.getByRole('button', { name: 'Create Enterprise Quote' }).click();
  await page.getByRole('combobox', { name: 'Price List Name' }).click();
  await page.getByRole('option', { name: 'IDR B2B Pricelist' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.locator('c-extended-b2b-cart-summary').getByRole('button', { name: 'Add Products' }).click();
  await page.getByText('Expand Tree BranchDigital').click();
  await page.getByRole('combobox', { name: 'Search' }).click();
  await page.getByRole('combobox', { name: 'Search' }).fill('iweb');
  await page.getByRole('combobox', { name: 'Search' }).press('Enter');
  await expect(page.getByTitle('Managed Anti-DDoS - iWeb App')).toBeVisible();
  await page.getByRole('button', { name: '+Add to Cart' }).click();
  await page.getByRole('button', { name: 'Add to Configuration Cart' }).click();
  await page.getByRole('button', { name: 'Sync Cart with validation and' }).click();
  await page.getByRole('button', { name: 'Collapsed' }).first().click();
  await page.getByRole('textbox', { name: '*Domain Names' }).click();
  await page.getByRole('textbox', { name: '*Domain Names' }).fill('example.com');
  await page.getByRole('button', { name: 'Collapsed' }).click();
  await page.locator('[id="One-2080 Time-2080 Price-2080"]').click();
  await page.locator('[id="One-2080 Time-2080 Price-2080"]').fill('25000000');
  await page.locator('[id="One-2080 Time-2080 Price-2080"]').press('Tab');
  await page.locator('.slds-m-left_xx-small > .slds-icon > use').click();
  await page.getByRole('button', { name: 'Back' }).click();
  await page.getByRole('combobox', { name: 'Search' }).click();
  await page.getByRole('combobox', { name: 'Search' }).fill('iweb');
  await page.getByRole('combobox', { name: 'Search' }).press('Enter');
  await page.getByRole('button', { name: '+Add to Cart' }).click();
  await page.getByRole('button', { name: 'Preview Cart (1)' }).click();
  await page.locator('c-extended-b2b-preview-cart').getByText('Managed Anti-DDoS - iWeb App').click();
  await page.getByRole('button', { name: 'Back' }).click();
});